'use strict';
const assert=require('node:assert/strict');const http=require('node:http');const net=require('node:net');const path=require('node:path');const test=require('node:test');
const {BackendProcessHost}=require('../../electron/desktopHost/BackendProcessHost');const {createInstalledResources}=require('./helpers');
const ROOT=path.resolve(__dirname,'../..');
function startOptions(){const r=createInstalledResources();return {entry:path.join(ROOT,'tests/wp2/fixtures/api-auth-desktop-entry.js'),cwd:ROOT,execPath:process.execPath,env:{...process.env},releaseStartupConfig:{resourcesPath:r.resourcesPath,expectedBuildId:r.manifest.buildId,manifestSha256:r.manifestSha256}};}
function waitMessage(child,type){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`${type} timeout`)),5000);const on=m=>{if(m?.type!==type)return;clearTimeout(timer);child.off('message',on);resolve(m);};child.on('message',on);child.once('error',reject);});}
function request(port,token){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port,path:'/api/ready',headers:token?{Authorization:`Bearer ${token}`}:{},timeout:2000},res=>{let body='';res.on('data',c=>body+=c);res.on('end',()=>resolve({status:res.statusCode,body:body?JSON.parse(body):{}}));});req.on('error',reject);req.end();});}
function upgrade(port,token){return new Promise((resolve,reject)=>{const socket=net.connect(port,'127.0.0.1',()=>{socket.write(`GET /events HTTP/1.1\r\nHost: 127.0.0.1:${port}\r\nConnection: Upgrade\r\nUpgrade: websocket\r\n${token?`Authorization: Bearer ${token}\r\n`:''}\r\n`);});let data='';const timer=setTimeout(()=>{socket.destroy();reject(new Error('upgrade timeout'));},2000);socket.on('data',c=>data+=c);socket.on('end',()=>{clearTimeout(timer);resolve(Number((data.match(/^HTTP\/1\.1\s+(\d+)/)||[])[1]||0));});socket.on('error',reject);});}

test('inherited pipe token is the actual HTTP and WebSocket authentication token',async()=>{const host=new BackendProcessHost();const started=await host.start(startOptions());const ready=await waitMessage(started.child,'api-auth-ready');assert.equal(ready.argvContainsToken,false);assert.equal(ready.environmentContainsToken,false);assert.equal((await request(ready.port,started.apiSessionToken)).status,200);const bad=await request(ready.port,'wrong-token');assert.equal(bad.status,401);assert.equal(bad.body.reasonCode,'API_SESSION_UNAUTHORIZED');assert.equal(await upgrade(ready.port,started.apiSessionToken),101);assert.equal(await upgrade(ready.port,'wrong-token'),401);await host.stop({gracefulMs:500,forceMs:1000});});

test('backend restart rotates token and old token is rejected by new backend',async()=>{const host=new BackendProcessHost();const first=await host.start(startOptions());const firstReady=await waitMessage(first.child,'api-auth-ready');assert.equal((await request(firstReady.port,first.apiSessionToken)).status,200);await host.stop({gracefulMs:500,forceMs:1000});const second=await host.start(startOptions());const secondReady=await waitMessage(second.child,'api-auth-ready');assert.notEqual(first.apiSessionToken,second.apiSessionToken);assert.equal((await request(secondReady.port,first.apiSessionToken)).status,401);assert.equal((await request(secondReady.port,second.apiSessionToken)).status,200);await host.stop({gracefulMs:500,forceMs:1000});});
