'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const test=require('node:test');
const {DesktopHost}=require('../../electron/desktopHost/DesktopHost');const {R32DesktopSettings,DESKTOP_NAMESPACE}=require('../../electron/r32DesktopSettings');const {DESKTOP_SETTING_KEYS,BUSINESS_SETTING_KEYS}=require('../../electron/desktopSettingsSchema');
const ROOT=path.resolve(__dirname,'../..');
function walk(dir){const out=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())out.push(...walk(f));else if(/\.(?:js|cjs|mjs)$/.test(e.name))out.push(f);}return out;}
function createStore(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'yance-wp2-settings-'));return{root,file:path.join(root,'desktop-settings.json'),store:new R32DesktopSettings(path.join(root,'desktop-settings.json'))};}

test('DesktopHost exposes only desktop process and credential custody responsibilities',()=>{const host=new DesktopHost({releaseManifestHost:{verify:()=>({buildId:'b'}),backendStartupConfig:()=>({resourcesPath:'/r',expectedBuildId:'b',manifestSha256:'a'.repeat(64)}),snapshot:()=>({buildId:'b'})},backendProcessHost:{snapshot:()=>({running:false}),start:async()=>({}),stop:async()=>({stopped:false}),restart:async()=>({})}});assert.equal(host.snapshot().role,'DESKTOP_HOST_ONLY');assert.throws(()=>host.executeControl('message.send',{}),e=>e.reasonCode==='DESKTOP_HOST_BUSINESS_COMMAND_FORBIDDEN');});

test('entire Electron production tree contains no business runtime, lifecycle manager, or generic command executor',()=>{const files=walk(path.join(ROOT,'electron'));const violations=[];for(const rel of ['electron/core/compositionRoot.js','electron/core/coreRuntime.js','electron/core/accountContext.js','electron/core/securityGuard.js'])if(fs.existsSync(path.join(ROOT,rel)))violations.push({file:rel,reason:'legacy-file-present'});const patterns=[/class\s+CoreRuntime\b/,/new\s+LifecycleManager\b/,/createDesktopCoreRuntime\b/,/desktop:core-command/,/\bdesktopCore\b/,/YANCE_SAFE_MODE/,/execute\s*\(\s*\{\s*command\s*:\s*['"](?:account|message|recovery|lifecycle)\./];for(const file of files){const text=fs.readFileSync(file,'utf8');for(const pattern of patterns)if(pattern.test(text))violations.push({file:path.relative(ROOT,file).replaceAll(path.sep,'/'),pattern:String(pattern)});}assert.deepEqual(violations,[]);});

test('Electron desktop settings expose an explicit desktop-only writable allowlist',()=>{assert.deepEqual(DESKTOP_SETTING_KEYS,[ 'windowX','windowY','windowWidth','windowHeight','windowMaximized','autoLaunch','minimizeToTray','closeToTray','startMinimized','theme','productSoundMode','gifAutoplay','stickerAutoplay','pauseAnimationWhenHidden','autoCheckUpdates','autoDownloadUpdates' ]);assert.equal(DESKTOP_SETTING_KEYS.some(k=>BUSINESS_SETTING_KEYS.includes(k)),false);});
for(const key of ['safeMode','autoConnectAccounts','backupOnStart','mediaAutoDownload'])test(`Electron rejects business setting ${key}`,()=>{const {store}=createStore();assert.throws(()=>store.update({[key]:true}),e=>e.reasonCode==='DESKTOP_BUSINESS_SETTING_FORBIDDEN');});

test('Electron settings writer stores only desktop JSON document',()=>{const {file,store}=createStore();const updated=store.update({closeToTray:false,theme:'dark',productSoundMode:'Immersive'});assert.equal(updated.closeToTray,false);assert.equal(updated.theme,'dark');assert.equal(updated.productSoundMode,'Immersive');const document=JSON.parse(fs.readFileSync(file,'utf8'));assert.equal(document.namespace,DESKTOP_NAMESPACE);assert.equal(document.key,'document');assert.equal(document.value.closeToTray,false);assert.equal(document.value.theme,'dark');assert.equal(document.value.productSoundMode,'Immersive');assert.equal(fs.existsSync(path.join(path.dirname(file),'yance-r32.db')),false);});

test('ipcGuardHandle delegates exactly once to ipcMain.handle instead of recursing',()=>{const source=fs.readFileSync(path.join(ROOT,'electron/main.js'),'utf8');assert.match(source,/function\s+ipcGuardHandle\(channel,\s*fn\)\s*\{\s*ipcMain\.handle\(channel,\s*m2Guard\(channel,\s*fn\)\);\s*\}/);assert.doesNotMatch(source,/function\s+ipcGuardHandle\(channel,\s*fn\)\s*\{\s*ipcGuardHandle\(/);});
test('desktop:update-settings production handler delegates to strict desktop-only store',()=>{const source=fs.readFileSync(path.join(ROOT,'electron/main.js'),'utf8');assert.match(source,/(?:ipcMain\.handle|ipcGuardHandle)\('desktop:update-settings',[\s\S]{0,220}settingsStore\.update/);assert.doesNotMatch(source,/desktop:update-settings[\s\S]{0,220}(?:safeMode|autoConnectAccounts|backupOnStart|mediaAutoDownload)/);});
