'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const test=require('node:test');
const {DESKTOP_FIELDS,RUNTIME_FIELDS,LIFECYCLE_FIELDS,splitSettingsPatch,saveSettingsPatch}=require('../../frontend/r32-settings-routing');
const ROOT=path.resolve(__dirname,'../..');
function adapters(){const calls={desktop:[],runtime:[],lifecycle:[]};return{calls,desktopUpdate:async patch=>(calls.desktop.push(patch),{...patch}),runtimeUpdate:async patch=>(calls.runtime.push(patch),{...patch}),lifecycleUpdate:async patch=>(calls.lifecycle.push(patch),{...patch})};}

test('closeToTray autoLaunch and desktop animation settings route only to Electron',async()=>{const a=adapters();const patch={closeToTray:false,autoLaunch:true,gifAutoplay:false,pauseAnimationWhenHidden:true};const result=await saveSettingsPatch({patch,...a});assert.deepEqual(a.calls.desktop,[patch]);assert.deepEqual(a.calls.runtime,[]);assert.deepEqual(a.calls.lifecycle,[]);assert.deepEqual(result.desktop,patch);});
test('autoConnectAccounts backupOnStart and mediaAutoDownload route only to backend runtime settings',async()=>{const a=adapters();const patch={autoConnectAccounts:false,backupOnStart:false,mediaAutoDownload:true};await saveSettingsPatch({patch,...a});assert.deepEqual(a.calls.desktop,[]);assert.deepEqual(a.calls.runtime,[patch]);assert.deepEqual(a.calls.lifecycle,[]);});
test('safeMode routes only to backend controlled lifecycle interface',async()=>{const a=adapters();await saveSettingsPatch({patch:{safeMode:true},...a});assert.deepEqual(a.calls.desktop,[]);assert.deepEqual(a.calls.runtime,[]);assert.deepEqual(a.calls.lifecycle,[{safeMode:true}]);});
test('mixed desktop and business patch is split so valid desktop fields are never sent to backend or rejected by Electron',async()=>{const a=adapters();await saveSettingsPatch({patch:{closeToTray:true,autoConnectAccounts:false,backupOnStart:true,mediaAutoDownload:false,safeMode:true},...a});assert.deepEqual(a.calls.desktop,[{closeToTray:true}]);assert.deepEqual(a.calls.runtime,[{autoConnectAccounts:false,backupOnStart:true,mediaAutoDownload:false}]);assert.deepEqual(a.calls.lifecycle,[{safeMode:true}]);});
test('desktop save completes before a backend runtime failure and receives no business field',async()=>{const calls=[];await assert.rejects(saveSettingsPatch({patch:{autoLaunch:true,autoConnectAccounts:true},desktopUpdate:async p=>{calls.push(['desktop',p]);return p;},runtimeUpdate:async p=>{calls.push(['runtime',p]);throw Object.assign(new Error('backend unavailable'),{reasonCode:'BACKEND_UNAVAILABLE'});}}),e=>e.reasonCode==='BACKEND_UNAVAILABLE');assert.deepEqual(calls,[['desktop',{autoLaunch:true}],['runtime',{autoConnectAccounts:true}]]);});
test('production frontend pages use the shared router and do not send business fields directly to desktop:update-settings',()=>{for(const file of ['frontend/r32-basic-settings.js','frontend/r32-settings-recovery.js','frontend/r32-system-center.js']){const text=fs.readFileSync(path.join(ROOT,file),'utf8');assert.match(text,/YanceSettingsRouting\.saveSettingsPatch/);for(const key of RUNTIME_FIELDS)assert.doesNotMatch(text,new RegExp(`updateSettings\\([^)]{0,300}${key}`),`${file}:${key}`);assert.doesNotMatch(text,/updateSettings\([^)]{0,300}safeMode/,file);}});
test('routing field sets are explicit and disjoint',()=>{const all=[...DESKTOP_FIELDS,...RUNTIME_FIELDS,...LIFECYCLE_FIELDS];assert.equal(new Set(all).size,all.length);const split=splitSettingsPatch(Object.fromEntries(all.map(key=>[key,true])));assert.deepEqual(Object.keys(split.desktop).sort(),[...DESKTOP_FIELDS].sort());assert.deepEqual(Object.keys(split.runtime).sort(),[...RUNTIME_FIELDS].sort());assert.deepEqual(Object.keys(split.lifecycle).sort(),[...LIFECYCLE_FIELDS].sort());});
