'use strict';
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const test=require('node:test');
const {ALLOWED_CONTROL_COMMANDS}=require('../../electron/desktopHost/DesktopHost');const {buildCommandPathInventory,collectActualIpc}=require('../../tools/wp2/command-path-inventory');const ROOT=path.resolve(__dirname,'../..');

test('DesktopHost control path contains only backend process lifecycle commands',()=>assert.deepEqual([...ALLOWED_CONTROL_COMMANDS].sort(),['backend.restart','backend.start','backend.status','backend.stop']));
test('production backend launch uses DesktopHost and no generic Electron core command path exists',()=>{const main=fs.readFileSync(path.join(ROOT,'electron/main.js'),'utf8');const preload=fs.readFileSync(path.join(ROOT,'electron/preload.js'),'utf8');assert.match(main,/backend['"],\s*['"]desktopHostedEntry\.js/);assert.match(main,/desktopHost\.startBackend\(/);assert.doesNotMatch(main,/\bfork\s*\(/);assert.doesNotMatch(main,/desktop:core-command|desktopCore/);assert.doesNotMatch(preload,/desktop:core-command|coreCommand/);});

test('complete production control-path inventory covers every actual Electron IPC and all authority fields',()=>{const rows=buildCommandPathInventory(ROOT);const actual=collectActualIpc(ROOT);const ipc=rows.filter(r=>r.entryKind==='ELECTRON_IPC');assert.equal(actual.length,45);assert.equal(ipc.length,45);assert.deepEqual(ipc.map(r=>r.channelOrCommandName).sort(),actual.map(r=>r.channel).sort());assert.equal(new Set(rows.map(r=>r.commandName)).size,rows.length);for(const row of rows){assert.ok(row.channelOrCommandName);assert.ok(row.finalAuthoritativePath);assert.ok(row.stateAuthorityOwner);assert.equal(typeof row.producesBusinessSideEffect,'boolean');if(row.entryKind==='ELECTRON_IPC'){assert.ok(row.electronIpcRegistration);assert.ok(row.electronExecutionModule);if(row.channelOrCommandName.startsWith('store:')){assert.equal(row.forwardingOnly,true);assert.match(row.backendRoute,/^\/api\/r32\/store\//);assert.equal(row.stateAuthorityOwner,'BACKEND_BUSINESS_RUNTIME');}}}
 for(const channel of ['desktop:restart-app','desktop:restart-backend','desktop:update-settings','desktop:save-credential','desktop:delete-credential','desktop:export-diagnostics','desktop:export-chat','desktop:open-auth-url','desktop:get-runtime-projection','desktop:set-operating-mode','desktop:set-titlebar-theme','desktop:preload-ready','desktop:renderer-ready','desktop:activation-probe-complete'])assert.ok(ipc.some(r=>r.channelOrCommandName===channel),channel);
 for(const channel of Object.values(require('../../electron/r32StoreBridge').CHANNELS))assert.ok(ipc.some(r=>r.channelOrCommandName===channel&&r.forwardingOnly&&r.backendRoute),channel);
});

test('desktop updater and backend runtime preparation have distinct command names and truthful modules',()=>{const rows=buildCommandPathInventory(ROOT);const ipc=rows.filter(r=>r.entryKind==='ELECTRON_IPC');for(const [channel,module] of [['desktop:update-get-state','electron/updateManager.js#snapshot'],['desktop:update-check','electron/updateManager.js#check'],['desktop:update-download','electron/updateManager.js#download'],['desktop:update-install','electron/updateManager.js#install']])assert.equal(ipc.find(r=>r.channelOrCommandName===channel)?.electronExecutionModule,module);
 for(const command of ['update.getRuntimeBlockers','update.preflight','update.prepareInstall']){const row=rows.find(r=>r.entryKind==='BACKEND_COMMAND'&&r.commandName===command);assert.ok(row);assert.equal(row.electronExecutionModule,null);assert.equal(row.backendExecutionModule,'backend/core/updateManager.js');}
 const names=new Set(rows.map(r=>r.commandName));for(const old of ['update.getState','update.check','update.install','update.download'])assert.equal(names.has(old),false,old);
});
