'use strict';
const test=require('node:test'); const assert=require('node:assert/strict');
const crypto=require('node:crypto'); const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path');
const {CredentialVault}=require('../../electron/credentialVault');
const {CredentialVaultHost}=require('../../electron/desktopHost/CredentialVaultHost');
const {makeCustodyRequest}=require('../../shared/credentialCustodyProtocol');
function storage(){const key=crypto.createHash('sha256').update('concurrency').digest();return{isEncryptionAvailable:()=>true,encryptString(v){const iv=Buffer.alloc(12,6),c=crypto.createCipheriv('aes-256-gcm',key,iv),body=Buffer.concat([c.update(String(v),'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),body]);},decryptString(v){const x=Buffer.from(v),d=crypto.createDecipheriv('aes-256-gcm',key,x.subarray(0,12));d.setAuthTag(x.subarray(12,28));return Buffer.concat([d.update(x.subarray(28)),d.final()]).toString('utf8');}};}
function setup(options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'wp4-concurrency-'));const vault=new CredentialVault(path.join(root,'vault.json'),{safeStorage:storage()});const host=new CredentialVaultHost({vault,metadataPath:path.join(root,'meta.json'),transactionPath:path.join(root,'journal.json'),randomUUID:()=> 'concurrency-epoch',...options});return{root,vault,host,close(){fs.rmSync(root,{recursive:true,force:true,maxRetries:10,retryDelay:50});}};}
async function hydrate(host){return (await host.createHydrationFrame({startupNonce:'n',oneTimeToken:'x'.repeat(43),backendPid:process.pid,manifestSha256:'a'.repeat(64)})).frame;}
function request(host,id,operation,ref,value){const m=host.snapshotMetadata();return makeCustodyRequest({action:'PREPARE',requestId:id,operation,ref,value,backendPid:process.pid,manifestSha256:'a'.repeat(64),vaultEpoch:m.vaultEpoch,generation:m.generation});}

test('FD6 PREPARE rejects desktop save as retryable, then both legal changes are retained',async()=>{const x=setup();try{await hydrate(x.host);const r=request(x.host,'fd6-save','persist','fd6/a',{a:1});await x.host.prepareCustodyTransaction(r);await assert.rejects(x.host.persistFromDesktop('desktop/b',{b:2}),e=>e.reasonCode==='CREDENTIAL_TRANSACTION_BUSY_RETRY'&&e.retryable===true);await x.host.commitCustodyTransaction({...r,action:'COMMIT'});await x.host.persistFromDesktop('desktop/b',{b:2});assert.deepEqual(x.vault.get('fd6/a'),{a:1});assert.deepEqual(x.vault.get('desktop/b'),{b:2});}finally{x.close();}});

test('FD6 PREPARE rejects desktop delete until ABORT releases the transaction reservation',async()=>{const x=setup();try{await x.host.persistFromDesktop('desktop/delete',{keep:true});await hydrate(x.host);const r=request(x.host,'fd6-abort','persist','fd6/pending',{p:1});await x.host.prepareCustodyTransaction(r);await assert.rejects(x.host.removeFromDesktop('desktop/delete'),e=>e.reasonCode==='CREDENTIAL_TRANSACTION_BUSY_RETRY');await x.host.abortCustodyTransaction({...r,action:'ABORT'});await x.host.removeFromDesktop('desktop/delete');assert.equal(x.vault.get('desktop/delete'),null);assert.equal(x.vault.get('fd6/pending'),null);}finally{x.close();}});

test('backend request arriving during desktop save is explicitly rejected on stale generation and succeeds after restart hydration',async()=>{let release;let enteredResolve;const entered=new Promise(r=>{enteredResolve=r;});const gate=new Promise(r=>{release=r;});let blocked=true;const x=setup({beforeTransactionCommit:async tx=>{if(blocked&&tx.source==='DESKTOP'){enteredResolve();await gate;blocked=false;}}});try{await hydrate(x.host);const desktop=x.host.persistFromDesktop('desktop/inflight',{d:1});await entered;const stale=request(x.host,'backend-stale','persist','fd6/after',{f:1});const backend=x.host.prepareCustodyTransaction(stale);release();await desktop;await assert.rejects(backend,e=>e.reasonCode==='CREDENTIAL_GENERATION_MISMATCH'&&e.retryable===true);const frame=await hydrate(x.host);const fresh=makeCustodyRequest({action:'PREPARE',requestId:'backend-fresh',operation:'persist',ref:'fd6/after',value:{f:1},backendPid:process.pid,manifestSha256:'a'.repeat(64),vaultEpoch:frame.vaultEpoch,generation:frame.generation});await x.host.prepareCustodyTransaction(fresh);await x.host.commitCustodyTransaction({...fresh,action:'COMMIT'});assert.deepEqual(x.vault.get('desktop/inflight'),{d:1});assert.deepEqual(x.vault.get('fd6/after'),{f:1});}finally{x.close();}});
