'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const crypto = require('node:crypto');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { CredentialVault } = require('../../electron/credentialVault');
const { CredentialVaultHost, AUTHORITY_HISTORY_MISMATCH, TERMINAL_JOURNAL_MISMATCH } = require('../../electron/desktopHost/CredentialVaultHost');
const { makeCustodyRequest } = require('../../shared/credentialCustodyProtocol');
function storage(){const key=crypto.createHash('sha256').update('terminal-recovery').digest();return{isEncryptionAvailable:()=>true,encryptString(value){const iv=Buffer.alloc(12,4),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),body=Buffer.concat([cipher.update(String(value),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]);},decryptString(value){const bytes=Buffer.from(value),decipher=crypto.createDecipheriv('aes-256-gcm',key,bytes.subarray(0,12));decipher.setAuthTag(bytes.subarray(12,28));return Buffer.concat([decipher.update(bytes.subarray(28)),decipher.final()]).toString('utf8');}};}
function setup(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'wp4-terminal-recovery-'));const paths={vault:path.join(root,'vault.bin'),metadata:path.join(root,'meta.json'),journal:path.join(root,'journal.json')};const vault=new CredentialVault(paths.vault,{safeStorage:storage()});const host=new CredentialVaultHost({vault,metadataPath:paths.metadata,transactionPath:paths.journal,randomUUID:()=> 'terminal-epoch'});host.createHydrationFrame({startupNonce:'n',oneTimeToken:'x'.repeat(43),backendPid:process.pid,manifestSha256:'a'.repeat(64)});return{root,paths,vault,host,close(){fs.rmSync(root,{recursive:true,force:true,maxRetries:10,retryDelay:50});}};}
function request(action,requestId,ref='provider/terminal',value={token:'redacted'},generation=1){return makeCustodyRequest({action,requestId,operation:'persist',ref,value,backendPid:process.pid,manifestSha256:'a'.repeat(64),vaultEpoch:'terminal-epoch',generation});}
function writeRaw(file,raw){fs.writeFileSync(file,`${JSON.stringify(raw,null,2)}\n`);}

test('COMMITTED journal with current metadata and unknown vault image fails closed',async()=>{const x=setup();try{const req=request('PREPARE','terminal-committed-mismatch');await x.host.prepareCustodyTransaction(req);await x.host.commitCustodyTransaction({...req,action:'COMMIT'});writeRaw(x.paths.vault,x.vault.prepareMutation('persist','unrelated',{value:true}).after);const reloaded=new CredentialVault(x.paths.vault,{safeStorage:storage()});assert.throws(()=>new CredentialVaultHost({vault:reloaded,metadataPath:x.paths.metadata,transactionPath:x.paths.journal,randomUUID:()=> 'terminal-epoch'}),error=>error.reasonCode===AUTHORITY_HISTORY_MISMATCH);}finally{x.close();}});

test('ROLLED_BACK journal with current metadata and unknown vault image fails closed',async()=>{const x=setup();try{const req=request('PREPARE','terminal-rolledback-mismatch');await x.host.prepareCustodyTransaction(req);await x.host.abortCustodyTransaction({...req,action:'ABORT'});writeRaw(x.paths.vault,x.vault.prepareMutation('persist','unrelated',{value:true}).after);const reloaded=new CredentialVault(x.paths.vault,{safeStorage:storage()});assert.throws(()=>new CredentialVaultHost({vault:reloaded,metadataPath:x.paths.metadata,transactionPath:x.paths.journal,randomUUID:()=> 'terminal-epoch'}),error=>error.reasonCode===AUTHORITY_HISTORY_MISMATCH);}finally{x.close();}});

test('ABORT journal failure happens before rollback side effects, makes live host unavailable, and restart preserves COMMITTED authority',async()=>{const x=setup();try{const req=request('PREPARE','abort-journal-failure');await x.host.prepareCustodyTransaction(req);await x.host.commitCustodyTransaction({...req,action:'COMMIT'});const committedGeneration=x.host.snapshotMetadata().generation;const originalSave=x.host._saveJournal.bind(x.host);let failed=false;x.host._saveJournal=()=>{if(!failed){failed=true;const error=new Error('rename EIO');error.code='EIO';throw error;}return originalSave();};await assert.rejects(x.host.abortCustodyTransaction({...req,action:'ABORT'}),error=>error.reasonCode===TERMINAL_JOURNAL_MISMATCH);assert.deepEqual(x.vault.getRequired('provider/terminal'),{token:'redacted'});assert.equal(x.host.snapshotMetadata().generation,committedGeneration);await assert.rejects(x.host.queryCustodyTransaction({...req,action:'QUERY'}),error=>error.reasonCode===TERMINAL_JOURNAL_MISMATCH);const diskJournal=JSON.parse(fs.readFileSync(x.paths.journal,'utf8'));assert.equal(diskJournal.transactions['abort-journal-failure'].state,'COMMITTED');const reloaded=new CredentialVault(x.paths.vault,{safeStorage:storage()});const restarted=new CredentialVaultHost({vault:reloaded,metadataPath:x.paths.metadata,transactionPath:x.paths.journal,randomUUID:()=> 'terminal-epoch'});const query=await restarted.queryCustodyTransaction({...req,action:'QUERY'});assert.equal(query.transactionState,'COMMITTED');assert.equal(query.persisted,true);assert.deepEqual(reloaded.getRequired('provider/terminal'),{token:'redacted'});assert.equal(restarted.snapshotMetadata().generation,committedGeneration);}finally{x.close();}});
