'use strict';
const test=require('node:test'); const assert=require('node:assert/strict'); const {Duplex}=require('node:stream');
const fs=require('node:fs'); const os=require('node:os'); const path=require('node:path'); const crypto=require('node:crypto');
const {CredentialVault}=require('../../electron/credentialVault');
const {CredentialVaultHost}=require('../../electron/desktopHost/CredentialVaultHost');
const {CredentialCustodyHost}=require('../../electron/desktopHost/CredentialCustodyHost');
const {CredentialCustodyClient}=require('../../backend/services/credentialCustodyClient');
function pair(){let a,b;a=new Duplex({read(){},write(c,e,cb){b.push(Buffer.from(c));cb();}});b=new Duplex({read(){},write(c,e,cb){a.push(Buffer.from(c));cb();}});return{a,b};}
function storage(){const key=crypto.createHash('sha256').update('txn-test').digest();return{isEncryptionAvailable:()=>true,encryptString(v){const iv=Buffer.alloc(12,7);const c=crypto.createCipheriv('aes-256-gcm',key,iv);const out=Buffer.concat([c.update(String(v),'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),out]);},decryptString(v){const x=Buffer.from(v),d=crypto.createDecipheriv('aes-256-gcm',key,x.subarray(0,12));d.setAuthTag(x.subarray(12,28));return Buffer.concat([d.update(x.subarray(28)),d.final()]).toString('utf8');}};}
function setup(options={}){const root=fs.mkdtempSync(path.join(os.tmpdir(),'wp4-txn-'));const vault=new CredentialVault(path.join(root,'vault.bin'),{safeStorage:storage()});const vh=new CredentialVaultHost({vault,metadataPath:path.join(root,'meta.json'),transactionPath:path.join(root,'txn.json'),randomUUID:()=> 'epoch-txn'});vh.createHydrationFrame({startupNonce:'n',oneTimeToken:'x'.repeat(43),backendPid:process.pid,manifestSha256:'a'.repeat(64)});const {a,b}=pair();let dropped=false;const host=new CredentialCustodyHost({stream:a,vaultHost:vh,context:{backendPid:process.pid,manifestSha256:'a'.repeat(64),vaultEpoch:'epoch-txn',generation:1},shouldDropAck:(req)=>options.dropCommitAck&&!dropped&&req.action==='COMMIT'?(dropped=true):false});const client=new CredentialCustodyClient({stream:b,timeoutMs:60,generation:1,context:{backendPid:process.pid,manifestSha256:'a'.repeat(64),credentialVaultEpoch:'epoch-txn',credentialGeneration:1}});return{root,vault,vh,host,client,close(){client.close();host.close();fs.rmSync(root,{recursive:true,force:true,maxRetries:10,retryDelay:50});}};}

test('ACK lost after Electron commit is recovered by QUERY and duplicate requestId is idempotent',async()=>{const x=setup({dropCommitAck:true});try{const opts={requestId:'req-ack-loss',prepareAuthority:async m=>m,commitAuthority:async()=>{},rollbackAuthority:async()=>{}};const first=await x.client.request('persist','telegram/session',{session:'secret'},opts);assert.equal(first.transactionState,'COMMITTED');assert.equal(x.client.snapshot().generation,2);assert.equal(x.client.snapshot().queryRecoveryCount,1);const second=await x.client.request('persist','telegram/session',{session:'secret'},opts);assert.equal(second.generation,2);assert.equal(x.vh.snapshotMetadata().generation,2);assert.deepEqual(x.vault.get('telegram/session'),{session:'secret'});}finally{x.close();}});

for(const [name,reason] of [['SQLite advanceCredentialGeneration failure','SQLITE_IO_ERROR'],['AppRuntime metadata failure','APP_RUNTIME_METADATA_FAILURE'],['expired fencing token','STALE_FENCING_TOKEN'],['read-only database','SQLITE_READONLY'],['SQLite I/O error','SQLITE_IOERR'],['backend shutdown','CREDENTIAL_BACKEND_SHUTTING_DOWN']]){
 test(`${name} rolls back vault and allows the next legal request`,async()=>{const x=setup();let fail=true;try{await assert.rejects(x.client.request('persist','provider/fail',{token:'secret'},{requestId:`fail-${reason}`,prepareAuthority:async m=>m,commitAuthority:async()=>{if(fail){fail=false;const e=new Error(name);e.reasonCode=reason;throw e;}},rollbackAuthority:async()=>{}}),e=>e.reasonCode===reason);assert.equal(x.vh.snapshotMetadata().generation,1);assert.equal(x.client.snapshot().generation,1);assert.equal(x.vault.get('provider/fail'),null);const ok=await x.client.request('persist','provider/ok',{token:'ok'},{requestId:`ok-${reason}`,prepareAuthority:async m=>m,commitAuthority:async()=>{},rollbackAuthority:async()=>{}});assert.equal(ok.generation,2);assert.deepEqual(x.vault.get('provider/ok'),{token:'ok'});}finally{x.close();}});
}
