'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { runDesktopCredentialApplicationLifecycleMatrix } = require('../../tools/wp4/desktop-credential-application-lifecycle-matrix');

const mutationCases = {
  M09_DESKTOP_BYPASSES_COORDINATOR: 'A01_REAL_SAVE_STOP_EXIT_COMMIT_FD5_READY',
  M18_APPLICATION_LEASE_OMITTED: 'A01_REAL_SAVE_STOP_EXIT_COMMIT_FD5_READY',
  M19_STOP_FAILURE_IGNORED: 'A03_STOP_FAILURE_AUTHORITY_UNCHANGED',
  M20_READY_FAILURES_IGNORED: 'A05_READY_GENERATION_MISMATCH_STOPS_REJECTED_OWNER',
  M21_READY_GENERATION_UNBOUND: 'A05_READY_GENERATION_MISMATCH_STOPS_REJECTED_OWNER',
  M22_READY_AUTHORITY_DIGEST_UNBOUND: 'A09_READY_DIGEST_MISMATCH_STOPS_REJECTED_OWNER',
  M23_IDEMPOTENT_REQUEST_ID_DISCARDED: 'A04_COMMIT_THEN_START_FAILURE_IDEMPOTENT_RESUME',
  M24_SHUTDOWN_BEFORE_COMMIT_IGNORED: 'A07_SHUTDOWN_AFTER_EXIT_BLOCKS_MUTATION',
  M25_REJECTED_NEW_OWNER_NOT_CLEANED: 'A05_READY_GENERATION_MISMATCH_STOPS_REJECTED_OWNER',
  M26_RUNTIME_PROJECTION_NOT_VALIDATED: 'A06_RUNTIME_PROJECTION_MISMATCH_STOPS_REJECTED_OWNER',
  M27_APPLICATION_INTERRUPTION_JOURNAL_IGNORED: 'A08_APPLICATION_RESTART_RECOVERS_COMMITTED_OPERATION',
  M28_UI_SUCCESS_BEFORE_RUNTIME_PROJECTION: 'A11_UI_SUCCESS_WAITS_FOR_RUNTIME_PROJECTION',
  M29_CLEANUP_FAILURE_RELEASES_APPLICATION_FENCE: 'A12_READY_GENERATION_MISMATCH_CLEANUP_STOP_FAILURE_CONTAINED',
  M30_CLEANUP_FAILURE_LEAVES_FD6_OPEN: 'A15_FD6_MISSING_CLEANUP_STOP_FAILURE_CONTAINED',
  M31_FAILED_SAFE_LIVE_OWNER_RESETS_IDLE: 'A23_FAILED_SAFE_LIVE_OWNER_CANNOT_RESET_IDLE',
  M32_ALREADY_READY_SKIPS_RUNTIME_PROJECTION: 'A22_ALREADY_READY_REVALIDATES_RUNTIME_PROJECTION',
  M33_LIVE_REJECTED_OWNER_ALLOWS_FD6_PREPARE: 'A16_LIVE_REJECTED_OWNER_FD6_PREPARE_DENIED',
  M34_CLEANUP_FAILURE_ALLOWS_UI_MUTATION: 'A24_LIVE_REJECTED_OWNER_UI_MUTATION_DENIED'
};

test('targeted Desktop Credential Application mutation oracle preserves the selected production invariant', async () => {
  const target = String(process.env.WP4_MUTATION_TARGET || '');
  const caseId = mutationCases[target];
  if (!caseId) {
    assert.equal(target, '');
    return;
  }
  const result = await runDesktopCredentialApplicationLifecycleMatrix({ caseIds: [caseId] });
  assert.equal(result.status, 'PASS');
  assert.equal(result.caseCount, 1);
  assert.equal(result.cases[0].id, caseId);
});
