homeserver:
  address: http://synapse:8008
  domain: yance.local
appservice:
  address: http://mautrix-whatsapp:29318
  hostname: 0.0.0.0
  port: 29318
  database:
    type: sqlite3-fk-wal
    uri: /data/mautrix-whatsapp.db
bridge:
  username_template: whatsapp_{{.}}
  displayname_template: '{{or .BusinessName .PushName .Phone}} (WhatsApp)'
  command_prefix: '!wa'
  permissions:
    '*': relay
    'yance.local': user
logging:
  min_level: info
