'use strict';

const RECENT_SOCIAL_MESSAGE_LIMIT = 60;
const MIN_INTERACTION_PREFERENCE_EVIDENCE = 3;
const FEEDBACK_ACTIVATION_EVIDENCE = 3;
const FEEDBACK_HISTORY_LIMIT = 200;

module.exports = {
  RECENT_SOCIAL_MESSAGE_LIMIT,
  MIN_INTERACTION_PREFERENCE_EVIDENCE,
  FEEDBACK_ACTIVATION_EVIDENCE,
  FEEDBACK_HISTORY_LIMIT
};
