'use strict';

const REASON_CODES = Object.freeze({
  EVIDENCE_SCHEMA_INVALID: 'EVIDENCE_SCHEMA_INVALID',
  EVIDENCE_PATH_INVALID: 'EVIDENCE_PATH_INVALID',
  EVIDENCE_TIMESTAMP_INVALID: 'EVIDENCE_TIMESTAMP_INVALID',
  EVIDENCE_COMMAND_DUPLICATE: 'EVIDENCE_COMMAND_DUPLICATE',
  EVIDENCE_CANONICAL_DIGEST_MISMATCH: 'EVIDENCE_CANONICAL_DIGEST_MISMATCH',
  EVIDENCE_RECEIPT_DIGEST_MISMATCH: 'EVIDENCE_RECEIPT_DIGEST_MISMATCH',
  EVIDENCE_COMMAND_SET_INVALID: 'EVIDENCE_COMMAND_SET_INVALID',
  EVIDENCE_COMMAND_SET_UNTRUSTED: 'EVIDENCE_COMMAND_SET_UNTRUSTED',
  EVIDENCE_COMMAND_SET_DIGEST_MISMATCH: 'EVIDENCE_COMMAND_SET_DIGEST_MISMATCH',
  EVIDENCE_EXECUTOR_UNKNOWN: 'EVIDENCE_EXECUTOR_UNKNOWN',
  EVIDENCE_EXECUTOR_REVOKED: 'EVIDENCE_EXECUTOR_REVOKED',
  EVIDENCE_EXECUTOR_GENERATION_MISMATCH: 'EVIDENCE_EXECUTOR_GENERATION_MISMATCH',
  EVIDENCE_PLATFORM_MISMATCH: 'EVIDENCE_PLATFORM_MISMATCH',
  EVIDENCE_EXECUTOR_ISOLATION_INVALID: 'EVIDENCE_EXECUTOR_ISOLATION_INVALID',
  EVIDENCE_EXECUTOR_ALGORITHM_INVALID: 'EVIDENCE_EXECUTOR_ALGORITHM_INVALID',
  EVIDENCE_EXECUTOR_COMMAND_SET_UNAUTHORIZED: 'EVIDENCE_EXECUTOR_COMMAND_SET_UNAUTHORIZED',
  EVIDENCE_SIGNATURE_INVALID: 'EVIDENCE_SIGNATURE_INVALID',
  EVIDENCE_BASE_MISMATCH: 'EVIDENCE_BASE_MISMATCH',
  EVIDENCE_HEAD_MISMATCH: 'EVIDENCE_HEAD_MISMATCH',
  EVIDENCE_REPOSITORY_MISMATCH: 'EVIDENCE_REPOSITORY_MISMATCH',
  EVIDENCE_COMMAND_FAILED: 'EVIDENCE_COMMAND_FAILED',
  EVIDENCE_COMMAND_RESULT_MISMATCH: 'EVIDENCE_COMMAND_RESULT_MISMATCH',
  EVIDENCE_ARTIFACT_DIGEST_MISMATCH: 'EVIDENCE_ARTIFACT_DIGEST_MISMATCH',
  EVIDENCE_WORKSPACE_DIRTY: 'EVIDENCE_WORKSPACE_DIRTY',
  EVIDENCE_WORKSPACE_HEAD_MISMATCH: 'EVIDENCE_WORKSPACE_HEAD_MISMATCH',
  EVIDENCE_UNEXPECTED_UNTRACKED_PATHS: 'EVIDENCE_UNEXPECTED_UNTRACKED_PATHS',
  EVIDENCE_CLI_ARGUMENT_INVALID: 'EVIDENCE_CLI_ARGUMENT_INVALID',
  EVIDENCE_SIGNATURE_FILE_INVALID: 'EVIDENCE_SIGNATURE_FILE_INVALID',
  EVIDENCE_ADAPTER_UNTRUSTED: 'EVIDENCE_ADAPTER_UNTRUSTED'
});

module.exports = { REASON_CODES };
